apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  labels:
    app: messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app
          image: messaging_app_image:latest  # Replace with your Docker Hub image if needed
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_DB
              value: "messaging_db"
            - name: MYSQL_PASSWORD
              value: "messaging_pass"
            - name: MYSQL_HOST
              value: "mysql-service"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  type: ClusterIP
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
