apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
  labels:
    app: messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: messaging-app
        version: blue
    spec:
      containers:
        - name: messaging-app
          image: messaging_app_image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_USER
              value: "messaging_user"
            - name: MYSQL_DB
              value: "messaging_db"
            - name: MYSQL_PASSWORD
              value: "messaging_pass"
            - name: MYSQL_HOST
              value: "mysql-service"
