version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment: # checker wants this section
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000  # checker wants python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
    depends_on:
      - db

volumes:
  db_data:
